[package]
name = "gideon-tax-form"
description = "US tax form schemas"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gideon-tax-core = { path = "../gideon-tax-core" }
